version: "3"
# version: "2"
services:
  database:
    container_name: "skomobo_db"
    image: mvertes/alpine-mongo
    ports: 
      - 27017:27017

    volumes: 
      - ./database:/data/db

    restart: always